default:
  aws_region: us-west-2
  aws_account_id: 970547372424

environments:
  dev:
    cluster: demo-cluster-dev
    aws_account_id: 970547372424
    services:
      demo_flask_app:
        ECR_REPOSITORY: demo-flask-app
        ECS_CLUSTER_NAME: demo-cluster
        ECS_SERVICE_NAME: demo-flask-app-service

  production:
    cluster: demo-cluster-prod
    aws_account_id: 970547372424
    services:
      demo_flask_app:
        ECR_REPOSITORY: demo-flask-app
        ECS_CLUSTER_NAME: demo-cluster
        ECS_SERVICE_NAME: demo-flask-app-service
